{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "protonmail-bridge.fullname" . }}-pvc
  labels:
    {{- include "protonmail-bridge.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- include "protonmail-bridge.storageClass" . | nindent 2 }}
{{- end }}
